---
driver:
  name: docker
  privileged: true
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /dev/fuse:/dev/fuse

provisioner:
  name: ansible_playbook
  hosts: localhost
  requirements_path: requirements.yml
  playbook: tests/test.yml
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

platforms:
  - name: "ubuntu-18-04"
    driver:
      instance_name: "ubuntu-18.04-puppet"
      image: diodonfrost/ubuntu-18.04-puppet
      run_command: /sbin/init
      platform: ubuntu
      provision_command:
        - apt-get install -y init
        - apt-get install -y fuse snapd snap-confine squashfuse sudo
        - dpkg-divert --local --rename --add /sbin/udevadm && ln -s /bin/true /sbin/udevadm

  - name: "ubuntu-16-04"
    driver:
      instance_name: "ubuntu-16.04-puppet"
      image: diodonfrost/ubuntu-16.04-puppet
      run_command: /sbin/init
      platform: ubuntu
      provision_command:
        - apt-get install -y init
        - apt-get install -y fuse snapd snap-confine squashfuse sudo
        - dpkg-divert --local --rename --add /sbin/udevadm && ln -s /bin/true /sbin/udevadm

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: spec/inspec

suites:
  - name: default
