---
dist: xenial
language: python
python:
  - "3.7"

before_install:
  - 'sudo rm -if /home/vagrant'
  - 'sudo apt-get update'

install:
  - 'wget https://packages.chef.io/files/stable/inspec/4.18.51/ubuntu/18.04/inspec_4.18.51-1_amd64.deb && sudo dpkg -i inspec_4.18.51-1_amd64.deb'
  - 'sudo python -m pip install ansible==2.9.3'
  - 'sudo env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install -r requirements.yml'

script:
  # Check syntax
  - 'sudo env ANSIBLE_FORCE_COLOR=1 ansible-playbook playbook.yml --syntax-check'

  # Run ansible playbook
  - 'sudo env ANSIBLE_FORCE_COLOR=1 ansible-playbook playbook.yml'

  # Test playbook
  - 'sudo inspec exec tests/inspec --chef-license accept-silent'
