---
- hosts: localhost
  remote_user: root
  vars_files:
    - defaults/main.yml

  roles:
    - diodonfrost.java
    - diodonfrost.puppet_agent
    - diodonfrost.packer
    - diodonfrost.vagrant
    - diodonfrost.terraform

  tasks:
    - include_tasks: tasks/main.yml
      tags: always
