---
- hosts:  localhost
  remote_user: root
  vars_files:
    - defaults/main.yml

  roles:
    - diodonfrost.packer
    # - diodonfrost.vagrant
    - diodonfrost.ohmyzsh
    - hurricanehrndz.rustup
    - geerlingguy.docker
    - fesaille.gh

  tasks:
    - include_tasks: tasks/main.yml
      tags: always
