---
# Install shell OhMyZsh

- name : List user with home directory
  shell: ls -1 /home
  register: list_user
  changed_when: false

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    update: no
  become: yes
  become_user: "{{ item }}"
  with_items:
    - "{{ list_user.stdout_lines }}"
    - "root"

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  become: yes
  become_user: "{{ item }}"
  with_items:
    - "{{ list_user.stdout_lines }}"
    - "root"

- name: Change user shell
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ list_user.stdout_lines }}"
    - "root"
