---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: linux
    image: diodonfrost/${image:-ansible-ubuntu:20.04}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/fuse:/dev/fuse
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
