---
# Install selected packages

- name: Install os packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_packages }}"

- name: Snapd service
  service:
    name: snapd
    state: started
    enabled: yes

- name: Install text editor Atom
  import_tasks: setup-atom.yml
  when: atom_install == true
  tags: atom

- name: Install awscli
  import_tasks: setup-aws-cli.yml
  when: awscli_install == true
  tags: awscli

- name: Install voice and text chat Discord
  import_tasks: setup-discord.yml
  when: discord_install == true
  tags: discord

- name: Install Docker
  import_tasks: setup-docker.yml
  when: docker_install == true
  tags: docker

- name: Install google cloud sdk
  import_tasks: setup-gcloud-sdk.yml
  when: gcloud_install == true
  tags: gcloud

- name: Install Kubernetes Minikube
  import_tasks: setup-minikube.yml
  when: minikube_install == true
  tags: minikube

- name: Install Puppet
  import_tasks: setup-puppet.yml
  when: puppet_install == true
  tags: puppet

- name: Install Slack
  import_tasks: setup-slack.yml
  when: puppet_slack == true
  tags: slack

- name: Install Vagrant
  import_tasks: setup-vagrant.yml
  when: vagrant_install == true
  tags: vagrant

- name: Install Virtualbox
  import_tasks: setup-virtualbox.yml
  when: virtualbox_install == true
  tags: virtualbox
