---
# Install Puppetlabs repos

- name: Add Puppetlabs signing key on Debian
  apt_key:
    url: http://apt.puppetlabs.com/DEB-GPG-KEY-puppetlabs
    state: present

- name: Add Puppetlabs repository on Debian
  apt:
    deb: https://apt.puppetlabs.com/puppet{{ puppet_version }}-release-{{ ansible_distribution_release }}.deb
    state: present

- name: Install puppet-agent
  package:
    name: puppet-agent
    update_cache: yes
    state: present
