---
# Install Virtualbox repos

- name: Add an virtualbox signing key on Debian
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add virtualbox repository on Debian
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: present

- name: Install virtualbox
  package:
    name: virtualbox
    ensure: present
