---
# Install Docker repos

- name: Install packages requirement for Docker
  package:
    name: "{{ item }}"
  with_items: "{{ docker_packages_requirement }}"

- name: Add an Docker signing key on Debian
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg
    state: present

- name: Add Docker repository on Debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: Service docker
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_virtualization_type != "docker"

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.0-rc2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
